### ISSUE TITLE
Lien 'Visiter la gallerie'

### ISSUE THREAD

**Issue by PmGs** [nikrou/phyxo#3]
A partir du menu administration il y a un lien 'Visiter la gallerie' qui renvoie à la visualisation des photos.

Ce lien renvoie à la racine du site, cad :
 - pour le site démo à dev.phyxo.net qui fonctionne
 - et pour mon site à .../phyxo/ qui ne fonctionne pas car il faudrait .../phyxo/index.php 

Je pense que la solution serait de rajouter index.php et que cela fonctionnera dans les 2 cas de figure.

**Comment by PmGs** [comment]
En fait j'avais introduit un index.html vide à la racine du site et c'est lui qui prenait la main avant l'index.php !

**Comment by nikrou** [comment]
Ok Je peux fermer du coup.

2015-04-26 11:08 GMT+02:00 PmGs <notifications@github.com>:
