### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by lwandrebeck** [nikrou/phyxo#5]
Hi,

CentOS 7, Phyxo 1.5.2, recently upgraded to PHP 7 via remi repo. Since then, upon login, I get 
Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: user (path: /var/lib/php/session) in /var/www/html/phyxo/src/Phyxo/Model/Repository/Users.php on line 316

PHP7 does work correctly, as several other php apps run flawlessly.

Thanks and keep up the good work :)

**Comment by nikrou** [comment]
I remove it in master branch. I need to refactor that code. By the way I think I will release Phyxo 1.6 soon

**Comment by lwandrebeck** [comment]
Thanks a lot for the new release. Anything particular to do to upgrade from 1.5.2 to 1.6.0 ? I couldn’t find any doc about it.

Thanks !

**Comment by nikrou** [comment]
Nothing special. Just click on upgrade button.

**Comment by lwandrebeck** [comment]
Well. I can’t login anymore due to incompatibility with php 7 ;)

**Comment by nikrou** [comment]
My bad. I will try to fix it.

**Comment by nikrou** [comment]
Fix in last release https://github.com/nikrou/phyxo/releases/tag/v1.6.1
