### ISSUE TITLE
Fatal error on install

### ISSUE THREAD

**Issue by franck-tomek** [nikrou/phyxo#70]
Just tried to install Phyxo 2.0.2 on a server with mysql / php 7.4 and got that error just after creating the user: 
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /home/lafr3189/galerie/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php:622`

Thanks.

**Comment by nikrou** [comment]
Issue not existing in more recent releases.
