### ISSUE TITLE
existing albums are not listed when trying to upload photos in admin area

### ISSUE THREAD

**Issue by lwandrebeck** [nikrou/phyxo#8]
CentOS 7, PHP 7.0.14, Postgres 9.6.1, Phyxo 1.6.1.

In admin area, no albums are listed when trying to upload new photos.

Moreover, an error message appears at the bottom of the page:
Fatal error: Uncaught RuntimeException: Unclosed string at position: 67069 in /var/www/html/phyxo/vendor/tedivm/jshrink/src/JShrink/Minifier.php:476 Stack trace: #0 /var/www/html/phyxo/vendor/tedivm/jshrink/src/JShrink/Minifier.php(231): JShrink\Minifier->saveString() #1 /var/www/html/phyxo/vendor/tedivm/jshrink/src/JShrink/Minifier.php(144): JShrink\Minifier->loop() #2 /var/www/html/phyxo/vendor/tedivm/jshrink/src/JShrink/Minifier.php(110): JShrink\Minifier->minifyDirectToOutput('/**\n * mOxie - ...', Array) #3 /var/www/html/phyxo/src/Phyxo/Template/FileCombiner.php(212): JShrink\Minifier::minify('/**\n * mOxie - ...') #4 /var/www/html/phyxo/src/Phyxo/Template/FileCombiner.php(196): Phyxo\Template\FileCombiner::process_js('/**\n * mOxie - ...', 'admin/themes/de...') #5 /var/www/html/phyxo/src/Phyxo/Template/FileCombiner.php(129): Phyxo\Template\FileCombiner->process_combinable(Object(Phyxo\Template\Script), true, false, NULL) #6 /var/www/html/phyxo/src/Phyxo/Template/FileCombiner.php(109): Phyxo\Template\FileCombiner->fl in /var/www/html/phyxo/vendor/tedivm/jshrink/src/JShrink/Minifier.php on line 476

**Comment by nikrou** [comment]
I confirm the problem. Thanks Laurent for report.
