### ISSUE TITLE
Latest version doesn’t work in admin area

### ISSUE THREAD

**Issue by lwandrebeck** [nikrou/phyxo#9]
CentOS 7, php 7.0.14, postgresql 9.6.1, phyxo 1.6.1.

Willing to upgrade to 1.6.2, in admin area, « Dernière version ? » link does not work ( admin/index.php?action=check_upgrade ).

Opening in a new tab gives « Impossible de connaître la dernière version ».

Keep up the good work !

**Comment by nikrou** [comment]
I confirm. :-(
A workaround is to update using the page Tools > Update (admin/index.php?page=updates)
